# Generated by Django 2.0.7 on 2018-10-15 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to='Course_Thumbnails/%Y/%m/%d/')),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prerequisite', models.TextField()),
                ('requirements', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('no_of_ratings', models.FloatField(default=0)),
                ('author', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('fees', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'permissions': (('access_course', 'Access Course'),),
            },
        ),
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('primary_registration_type', models.CharField(choices=[('Learner', 'Learner'), ('Trainer', 'Trainer')], max_length=15)),
                ('secondary_registration_type', models.CharField(blank=True, choices=[('Learner', 'Learner'), ('Trainer', 'Trainer')], max_length=15)),
                ('tertiary_registration_type', models.CharField(blank=True, choices=[('Learner', 'Learner'), ('Trainer', 'Trainer')], max_length=15)),
                ('quaternary_registration_type', models.CharField(blank=True, choices=[('Learner', 'Learner'), ('Trainer', 'Trainer')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics/%Y/%m/%d/')),
                ('courses_tutoring', models.TextField()),
                ('describe_yourself', models.TextField()),
                ('linked_in_url', models.URLField()),
                ('skills', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, upload_to='cvs/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Custom_User')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Trainer_Model'),
        ),
    ]
